### ISSUE TITLE
Both match games

### ISSUE THREAD

**Issue by A1rPun** [zoul0813/angularjs-match#1]
I stumbled upon your match game but both versions have a little something.

- [The original](http://projects.zoulcreations.com/jquery/match/) is too easy ;)
![1568643092](https://user-images.githubusercontent.com/3754692/64965159-c4d06400-d89c-11e9-8d20-0220894b0c26.png)

- Apart from the php error on [the blog](http://www.fragmentedcode.com/2014/02/09/memory-match-built-with-angularjs-and-bootstrap-3/) .. when you click on a card in http://projects.zoulcreations.com/jquery/angularjs-match/ .. other cards shift across rows which makes the memory game too hard.
![1568643183](https://user-images.githubusercontent.com/3754692/64965238-e9c4d700-d89c-11e9-89e4-e032876f1fdb.png)

**Comment by zoul0813** [comment]
I appreciate the feedback, but both of those were examples written many years ago.

Neither is supported today, and both are based on obsolete/deprecated library versions.

They were meant as examples, for learning, not as practical games for entertainment.

**Comment by A1rPun** [comment]
Thanks ;)
